GP_PRESCRIPTIONS = ['** BABY WEIGHT REQUIRED**  Dose is 0.8ml/kg bodyweight as a single dose repeated after 14 days',
'** BABY WEIGHT REQUIRED** Dose is 0.3 to 0.5ml/kg bodyweight once a day for 7 days.',
'**BABY WEIGHT REQUIRED** Dose is 0.8ml per kg bodyweight per day divided into 3 doses',
'**BABY WEIGHT REQUIRED** Dose is 0.8ml per kg bodyweight per day divided into 3 doses. Take for 3 days only.',
'**BABY WEIGHT REQUIRED** Dose is 1 to 2mg per kg bodyweight per day for 1 day',
'**BABY WEIGHT REQUIRED** Dose is 1 to 2mg per kg bodyweight per day for 3 days',
'**BABY WEIGHT REQUIRED** Dose is 1 to 2mg per kg bodyweight per day for 5 days',
'**BABY WEIGHT REQUIRED** Dose is 10mg per kg bodyweight per day for 3 days',
'**BABY WEIGHT REQUIRED** Dose is 7.5 mg per kg bodyweight twice a day for 5 days',
'**BABY WEIGHT REQUIRED** Dose is 7.5 mg per kg bodyweight twice a day for 7 days',
'**BABY WEIGHT REQUIRED** Dose is 7.5mg per kg bodyweight twice a day for 3 days',
'**BODY WEIGHT REQUIRED**Take 3mg/kg daily divided into 4 doses',
'**WEIGHT MAY BE REQUIRED** Take one 5ml spoonful daily. If necessary, dose may be increased to a maintenance dose of 20mg per kg daily',
'**WEIGHT REQUIRED** Dose is 20mg per kg daily in divided doses',
'**WEIGHT REQUIRED** Initial dose is 400mg daily in divided doses, this may be increased if required to a maximum of 35mg per kg daily.',
'**WEIGHT REQUIRED** Take 0.075mg (0.25ml) per kg three times a day',
'*WEIGHT REQUIRED*  Dose is 1mg/kg bodyweight as a single dose at night',
'*WEIGHT REQUIRED*  Take 7.5mg/kg every 8 hours for 5 days',
'*WEIGHT REQUIRED* Dose is 10 to 12.5mg per kg as a single dose at night, up to a maximum of 125mg.',
'*WEIGHT REQUIRED* Take 7.5mg/kg every 8 hours for 7 days',
'0.75mg/kg 4 times a day',
'0.75mg/kg every 4 to 6 hours when required for pain relief. Maximum of 4 doses in 24 hours',
'1 pair of Compression Class II stockings thigh length',
'10mg/kg every 4 to 6 hours when required. Maximum of 4 doses in 24 hours',

'2 sprays into each nostril two to three times daily',
'AA',
'"ACBS"  - use as baby milk',
'Add 15ml to the bathwater',
'Add 30ml to the bathwater',
'Add 5-15 mL to an 8 inch deep bath of water',
'Apply 1 to 2 g to vagina, once a day for 1 week. Reduce as condition improves,  to  alternate days for 2 weeks more, then stop',
'Apply 1/2inch of gel with gentle massage as required, but not more than every 3 hours',
'Apply 1/4inch of gel with gentle massage as required, but not more than 6 times a day',
'Apply 2 to 3 drops into affected ear(s) every three to four hours',
'Apply 2 to 3 drops into affected ear(s) four times a day',
'Apply 2 to 3 drops into affected ear(s) three to four times a day',
'Apply 2 to 3 drops into affected ear(s) twice a day',
'Apply 2 to 3 drops into affected ear(s) two to three times a day',
'Apply 2 to 4 drops into affected ear(s) three to four times a day and at night',
'Apply 2.5 centimetres (1 inch) to the affected area, two to four times daily for 2 weeks.',
'Apply 2-4 g (about 1 or 2 penny piece size) to the affected area, three or four times a day for two weeks',
'Apply 3 drops into affected ear(s) every four hours',
'Apply 3 drops into affected ear(s) four times a day',
'Apply 3 drops into affected ear(s) twice a day',
'Apply 3cm (about 1 and 1/4 inch) to the affected area, three or four times a day for 2 weeks',
'Apply 4 to 10 centimetres (1.5-4 inches) to the affected area, three or four times daily for 2 weeks',
'Apply 5 to 10 centimetres (1.5-4 inches) to the affected area, two or three times daily for 10 days.',
'Apply a new patch once a week following instructions on pack',
'Apply a new patch twice a week and take one tablet daily for the 12 days as instructed on pack',
'Apply a new patch twice a week following instructions in pack, using small patches for first 2 weeks then larger patches for second 2 weeks.',
'Apply a new patch twice a week following instructions on pack',
'Apply a new patch twice a week following instructions on pack and take one tablet daily for 14 days following instructions on pack.',
'Apply a thin layer two to four times a day to affected area(s), do not rub in.',
'Apply all over body except near eyes and mouth. Wash off after 24 hours.',
'Apply all over body.Allow to dry naturally.  Leave on for 12 hours. Wash off.',
'Apply as required',
'Apply at every nappy change',
'Apply at every nappy change',
'Apply daily as directed by your doctor',
'Apply morning and night and after a bowel movement',
'Apply once daily at night; reduce frequency of application as condition improves or if irritation occurs',
'Apply once daily for up to 5 days;  for prevention may be used once daily for up to 3 days as a single treatment before exposure to the sun',
'Apply once each day',
'Apply once or twice a day to clean skin',
'Apply once or twice a week to the affected nail(s).',
'Apply once or twice each day',
'Apply one spray into each nostril as required to maximum of twice an hour for 16 hours (maximum 64 sprays daily).',
'Apply patch to non hairy area of trunk or upper arm every morning.',
'Apply patch to non hairy area of trunk or upper arm every morning. Remove 16 hours later usually at bedtime.',
'Apply sparingly 2 or 3 times a day initially, then reduce to once a day, for up to 7 days',
'Apply sparingly if required',
'Apply sparingly several times daily if required',
'Apply sparingly to scalp once or twice daily',
'Apply sparingly to the affected area twice a day',
'Apply thinly  twice each day',
'Apply thinly once or twice each day',
'Apply thinly once or twice each day for 3 days',
'Apply thinly to clean skin, once or twice a day',
'Apply thinly to the affected area twice a day, continuing for seven days after area has healed.',
'Apply thinly to the affected areas on the scalp once or twice each day',
'Apply thinly twice each day for up to 7 days',
'Apply three times each day for 5 days',
'Apply to affected area 2-3 times daily',
'Apply to affected area twice a day',
'Apply to affected area(s) for 30-60 minutes once each day then wash off',
'Apply to affected areas for 30 minutes once each day then wash off',
'Apply to affected areas on scalp once each day for 3 to 7 days then once each week thereafter.  Shampoo off after one hour.',
'Apply to affected eye(s) at night',
'Apply to affected eye(s) four times a day',
'Apply to affected eye(s) twice daily',
'Apply to clean damp hair. Leave on for 10 minutes then wash off.',
'Apply to clean skin twice a day',
'Apply to cold sore every 2 hours during waking hours for 4 days',
'Apply to cold sore every 4 hours (5 times a day) for 5 days',
'Apply to dry hair and scalp.Leave to dry naturally.Comb and wash off after 12 hours.',
'Apply to eyelid margins four times a day',
'Apply to eyelid margins twice a day',
'Apply to inner surface of both nostrils four times each day for 5 days',
'Apply to large areas such as the back. Apply thinly to clean skin once or twice a day',
'Apply to outer affected area twice daily',
'Apply to the affected area',
'Apply to the affected area as directed.',
'Apply to the affected area three times daily, continuing for seven days after affected areas have healed',
'Apply to the affected area(s) at night then wash off the next morning',
'Apply to the affected area, thinly, 2 to 3 times a day, reducing frequency as the condition responds',
'Apply to the affected area, thinly, 2 to 3 times a day. Reduce frequency as the condition responds.',
'Apply to the affected area, thinly, once or twice a day, reducing frequency as the condition responds',
'Apply to the affected area, thinly, up to 4 times a day, reducing the frequency as condition responds.',
'Apply to the affected areas on the scalp twice each day',
'Apply to the affected areas on the scalp twice each day',
'Apply to the affected nail(s) and surrounding skin twice a day. Treatment should continue for up to six months.',
'Apply to the lower lid margin of the affected eye(s) 4 times a day.',
'Apply to the lower lid margin of the affected eye(s) at night. Continue for 48 hours after the infection has cleared.',
'Apply twice a day as directed',
'Apply twice a week, rinse hair thoroughly',
'apply twice each day',
'Apply twice each day and for at least 14 days after area has improved',
'Apply twice each day for 1 week',
'Apply twice each day for at least a week after area has improved',
'Apply twice each day, continuing for a few days after affected areas have healed',
'Apply twice weekly for 2-4 weeks until condition improves then once weekly',
'Apply two measures once a day to the arms, shoulders or inner thighs as directed.',
'Apply two or three times each day for at least a week after area has improved',
'Apply when required',
'Appy cream to affected joint twice daily',
'Chew 1 or 2 tablets four times a day after meals and at bedtime',
'Chew each piece slowly for 30 minutes in place of a cigarette, maximum 15 daily.',
'Chew one or two tablets up to 1 hour after meals and at bedtime',
'Chew one to three tablets after meals and at bedtime',
'Chew one to two tablets after meals and at bedtime, followed by water',
'Dissolve one in water. Use as a gargle then swallow.',
'Dissolve one tablet in 4 litres of water. Apply the solution as wet dressings',
'Follow the instructions given inside this pack.',
'Follow the instructions on the pack',
'For deep intramuscular injection',
'For deep intramuscular injection - 40 - 120mg',
'For deep intramuscular injection - 40-80mg - into gluteal muscle',
'For deep intramuscular injection - 5 - 80mg.',
'For deep intramuscular injection into gluteal muscle',
'For examination of the eye',
'For IM or deep SC injection only',
'For insertion into the uterine cavity',
'For intramuscular injection',
'For intramuscular injection, once every 4 weeks.',
'FOR INTRAMUSCULAR INJECTION. Inject the contents of one ampoule (1mg) every 2 to4 days for six doses, then every 3 months thereafter.',
'FOR INTRAMUSCULAR INJECTION. Inject the contents of one ampoule (1mg) every 3 months.',
'For intramuscular or subcutaneous injection, once every 4 weeks.',
'For intravenous injection',
'For local anaesthetic  injection.',
'For reconstitution',
'For su dermal implantation',
'For subcutaneous implantation as directed by your doctor',
'For subcutaneous implantation, once every 4 weeks.',
'For subcutaneous injection once every 4 weeks',
'For subcutaneous injection or continous subcutaneous infusion',
'For subdermal implantation',
'For use in reversibility test.',
'fouy',
'Give 2 to 3 sprays into mouth up to four times a day',
'Give one dropperful (0.5ml) before each feed. Increase to 2 dropperfuls (1ml ) if required.',
'Inhale 1 or 2 puffs as required',
'Inhale 1 or 2 puffs three or four times a day',
'Inhale 1 puff as required',
'Inhale 1 puff twice a day',
'Inhale 1 to 2 puffs twice a day',
'Inhale 10mg (2 respules) using nebuliser repeated two to four times daily',
'Inhale 2 puffs as required up to four times a day',
'Inhale 2 puffs every six to eight hours',
'Inhale 2 puffs four times a day',
'Inhale 2 puffs six to eight times a day',
'Inhale 2 puffs three times a day',
'Inhale 2 puffs twice a day',
'Inhale 2 puffs twice a day, increasing to 3 or 4 times a day if required',
'Inhale 2.5mg using nebuliser up to four times a day',
'Inhale 2mg (0.2ml, diluted to required nebuliser volume with sterile physiological saline) 2 to 4 times a day',
'Inhale 2mg (0.2ml, diluted to required nebuliser volume with sterile 0.9% sodium chloride) 2 to 4 times a day',
'Inhale 3 puffs four times a day',
'Inhale 3 puffs twice a day',
'Inhale 3mg (0.3ml, diluted to required nebuliser volume with sterile 0.9% sodium chloride)2 to 4 times a day',
'Inhale 4 or 5 puffs twice a day',
'Inhale 4 puffs four times a day',
'Inhale 4 puffs twice a day',
'Inhale 4 to 6 puffs as required  up to four times a day',
'Inhale 5 puffs four times a day',
'Inhale 500 micrograms using nebuliser up to 4 times a day.',
'Inhale 5mg using nebuliser repeated two to four times a day',
'Inhale 5mg using nebuliser up to four times a day',
'Inhale 6 puffs four times a day',
'Inhale four puffs twice a day',
'Inhale inplace of a cigarette, use between 6 and 12 cartridges a day for up to 8 weeks then reduce.',
'Inhale inplace of cigarette, use between 6 and 12 cartridges a day.',
'Inhale one or two puffs four times a day',
'Inhale one puff four times a day',
'Inhale one puff if required up to 3 or 4 times a day.',
'Inhale one puff once a day',
'Inhale one puff three or four times a day',
'Inhale one puff twice a day',
'Inhale one puff twice a day, increasing to three or four times a day if required.',
'Inhale one to three puffs if required up to 4 times a day.',
'Inhale one to two puffs 3 or 4 times a day',
'Inhale one to two puffs up to three or four  times a day',
'Inhale ten successive puffs, for reversibility test.',
'Inhale the contents of 1 capsule  four  times a day using spinhaler',
'Inhale the contents of 1 capsule eight times a day using spinhaler',
'Inhale the contents of one nebule (2.5mg) every 3 to 4 hours using nebuliser',
'Inhale three puffs twice a day',
'Inhale two puffs twice a day.',
'Inhale two to six puffs if required up to four times a day.',
'Inject as local anaesthetic',
'Inject into large joint  4 - 80 mg according to joint size',
'Inject into large joint 2-30mg according to joint size',
'Inject into large joint as directed',
'Inject into large joint mixed with local anaesthetic injection',
'Inject into small joint 5- 50 mg according to size',
'Inject into small joint 5-25mg according to joint size',
'Inject into small joint as directed',
'Inject into small joint mixed with local anaesthetic injection',
'Inject the contents of one syringe (6mg) subcutaneously at onset of migraine. Repeat after not less than 1 hour if migraine recurs.',
'Insert 1 pessary into the vagina twice a day for 7 days and apply cream to outer affected area twice a day.',
'Insert 1 pessary into the vagina twice a day for 7 days.',
'Insert 1 pessary into vagina every night  for 3 nights. Repeat every 2 to 4 weeks as directed.',
'Insert 1 pessary into vagina one at night as a single dose and repeat every 2 to 4 weeks as directed.',
'Insert 10mg (one tube) into the rectum as directed',
'Insert 1applicatorful into vagina each evening. Reduce as condition improves to treatment twice a week.',
'Insert 20mg into the rectum as directed.',
'Insert 5g applicator full into vagina twice a day for 7 days. Repeat every 2 to 4 weeks as directed.',
'Insert 5g applicator full into vagina twice daily for 7days',
'Insert 5g into vagina at night as a single dose',
'Insert 5g into vagina at night as a single dose. Repeat every 2 to 4 weeks as directed.',
'Insert 5mg into the rectum as directed',
'Insert 5mg into the rectum halfway to mark on nozzle as directed',
'Insert into rectum - if no response after 5 minutes, repeat once',
'Insert into rectum as directed',
'Insert into rectum half way to mark on nozzle- if no effect after 5 minutes, repeat once',
'Insert into rectum halfway to mark on nozzle',
'Insert into vagina one at night as single dose',
'Insert into vagina one at night as single dose for 3 nights',
'Insert one applicatorful into the vagina every night for 5 nights',
'Insert one applicatorful into the vagina every night for 7 nights',
'Insert one applicatorful into the vagina twice a day',
'Insert one into the rectum during an acute attack.',
'Insert one into the rectum when required. Maximum 1 in 24 hours',
'Insert one into the rectum when required. Maximum 2 in 24 hours.',
'Insert one into the vagina at night as a single dose',
'Insert one or two into the rectum every 4 to 8 hours when required for nausea and vomiting',
'Insert one or two suppositories into the rectum up to four times a  day',
'Insert one pessary high up into vagina every evening, until improvement occurs, then reduce to one pessary twice a week.',
'Insert one pessary into vagina daily for 2 weeks then reduce to twice a week as directed',
'Insert one pessary into vagina every night for 6 nights',
'Insert one ring high into vagina and wear continuously for 3 months',
'Insert one suppository into the rectum as required',
'Insert one suppository into the rectum at night and after a bowel movement',
'Insert one suppository into the rectum every morning and night',
'Insert one suppository into the rectum in the morning as needed.',
'Insert one suppository morning and night and after a bowel movement',
'Insert one tube into rectum as directed',
'Insert pessary into vagina one at night as a single dose and apply cream to outer affected  area 2-3 times a day for 3 days',
'Insert pessary into vagina one at night as a single dose and apply cream to outer affected area twice a day for 3 days',
'Insert pessary into vagina one at night for 3 days and apply cream to outer  affected area twice a day.',
'Instill 3 to 4 drops into affected ear(s) four times a day for 5 days',
'Instill into affected eye(s) every 30minutes initially then as required',
'Instill into affected eye(s) five times daily',
'Instill into eyes every 2 to 3 hours as necessary',
'Instill one drop into affected eye(s) every 3 hours initially then four times a day',
'Instill one drop into affected eye(s) every 3 hours initially then three times a day, using ointment at night.',
'Instill one drop into affected eye(s) four times a day',
'Instill one drop into affected eye(s) twice a day',
'Instill one drop into affected eye(s) twice a day. May increase to 3 or 4 times a day. Discontinue if no improvement within 3 days.',
'Instill one drop into affected eye(s) twice a day. May increase to four times a day if required.',
'Instill one drop into affected eye(s) two or three times a day',
'Instill one or two drops into affected eye(s) three or four times a day',
'Let one pellet dissolve slowly over the affected area four times a day',
'One pair of Class II compression, circular knit, thigh length stockings to be measured and fitted in the pharmacy',
'One spray into each nostril at bedtime.',
'Oxygen required for ______ hours per day at flow rate ______',
'Oxygen required for ______hours per day at flow rate  ______. Supply with nasal cannula.',
'Place one tablet under the tongue as required for chest pain.',
'Place tablet between upper lip and gum, and leave to dissolve for chest pain.',
'Put 2 drops into each nostril twice daily',
'Put one drop in the affected eye(s) 2 or 3 times a day',
'Put one drop in the affected eye(s) 4 times a day',
'Put one drop in the affected eye(s) every 2 hours, reducing to 4 times a day as improves. Continue for 48 hours after infection has cleared',
'Put one drop in the affected eye(s) twice a day. Continue for 48 hours after the infection has cleared',
'Put one or two drops in both nostrils up to 3 or 4 times a day when required',
'Put one or two drops in each nostril once or twice a day when required. Do not use for more than 5 days.',
'Put one or two drops in each nostril once or twice a day when required. Do not use for more than 7 days.',
'Put one or two drops in the affected eye(s) 2 or 3 times a day',
'Put two or three drops in each nostril 2 to 3 times a day when required. Do not use for more than 7 days.',
'Put two or three drops into each nostril two or three times a day when required. Do not use for more than 5 days.',
'Reconstitute with water for injection and give by slow intravenous injection at once.',
'Rinse the mouth with 10ml for about 1 minute twice a day',
'Rub into affected areas on scalp each night then shampoo off in the morning.',
'Spray 1 or 2 puffs in the affected nostril(s) up to 4 times a day',
'Spray 1 puff under the tongue as required for chest pain',
'Spray one puff  into one nostril every morning and the other nostril at night',
'Spray one puff in each nostril 2 to 3 times a day when required. Do not use for more than 7 days.',
'Spray one puff into each nostril three times a day',
'Spray one puff into each nostril two to four times a day',
'Spray two puffs in each nostril twice a day',
'Swallow one capsule, whole with water, three times a day before meals',
'Swallow one or two capsules whole with water, three times a day',
'Swallow the granules from one capsule with soft food, twice a day',
'Take 0.4ml per kg bodyweight each day',
'Take 0.8ml per kg bodyweight per day divided into 3 doses',
'Take 1 capsule as a single dose by mouth. Repeat every 2 to 4 weeks as directed.',
'Take 1 capsule at night for 4 nights, then increase to 2 capsules at night for 4 nights',
'Take 1 capsule at night for 4 nights, then increase to 3 capsules at night for next 4 nights, then increase to 5 capsules at night',
'Take 1 capsule at night for 5 days, then take 2 capsules at night',
'Take 1 capsule twice a day for one week, then increase by 1 capsule each week until pain settles, up to a maximum of 6 capsules daily.',
'Take 1 or 2  tablets every four hours when necessary. Maximum 8 tablets in 24 hours.',
'Take 1 or 2 tablets every four hours. Maximum 8 tablets daily.',
'Take 1 tab at night for 2 weeks, then take 2 tabs at night for 2 weeks, then 3 tabs at night for 2 weeks, then 4 tabs at night for 2weeks',
'Take 1 tab at night for 4 nights, then take 2 tabs at night for next 4 nights, then 3 tabs at night for 4 nights and then 4 tabs at night',
'Take 1 tablet at night for 3 nights, then take 2 tabs at night for 3 nights, then take 3 tablets at night thereafter',
'Take 1 tablet at night for 7 nights, then increase to 1 tablet twice a day for 7 days, then increase to 2 tablets twice a day for 7 days.',
'Take 1 tablet at night for 7 nights, then take 2 tabs at night for 7 nights, then 3 tabs at night for 7 nights then 4 tabs at night for 7 nights',
'Take 1 tablet at night for two weeks, then take 2 tabs at night for 2 weeks, then take 3 tabs at night for 2 weeks, then 4 tabs at night',
'Take 1 tablet daily for 7 days, then increase by 1 tablet each week as directed until pain settles, up to a maximum of 6 tablets daily.',
'Take 1 tablet every four to six hours when necessary. Maximum 6 tablets in 24 hours.',
'Take 1 tablet every four to six hours. Maximum 6 tablets daily.',
'Take 1 tablet every three to four hours when necessary. Maximum  6 tablets in 24 hours.',
'Take 1 tablet every three to four hours when required for pain relief , up to a maximum  of 8 tablets in 24 hours.',
'Take 1 tablet nocte for 4 nights, then 1 tablet twice daily for 1 week, then 2 tablets twice daily for 1 week, then 2 tablets twice daily and 4 nocte',
'Take 1 tablet nocte for 4 nights, then take 1 tablet twice daily for 1 week, then 2 tablets twice a day for 1 week, then 2 tablets three times a day',
'Take 1/2 a tablet twice a day increasing if needed after 3 days to 1/2 a tablet three times a day, then after a further 3 days to 1 tablet twice a day',
'Take 1/3rd sachet now as a single dose. Repeat after 2 weeks.',
'Take 1/3rd sachet now.',
'Take 10 to 20ml after meals and at bedtime when required',
'Take 10 to 20mls 1 hour after food and at bedtime, or as required.',
'Take 10 to 20mls up to one hour after meals and at bedtime',
'Take 10mg per kg bodyweight per day for 3 days',
'Take 10ml three times a day for two days only. Dilute each dose in a glass of water.',
'Take 10ml three times daily, well diluted in water',
'Take 10ml to 25ml at night as directed',
'Take 10ml twice a day',
'Take 10ml twice a day for 7 days.',
'Take 10mls three times a day in water',
'Take 15ml twice a day',
'Take 15ml twice a day',
'Take 2 tablets at night for 4 nights, then increase to 2 tablets twice daily for 1 week, then take 2 tablets twice a day and 4 tablets at night',
'Take 2 tablets daily for 7 days, then increase by 1 tablet each week as directed until the pain settles, up to a maximum of 6 tablets daily',
'Take 2.5 to 5ml three or four times a day when required',
'Take 2.5ml 3 times a day when required',
'Take 2.5ml at night if needed',
'Take 2.5ml at night.',
'Take 2.5ml at night. Increase up to 2.5ml three times a day if needed.',
'Take 2.5ml every 4 to 6 hours at first, then increase to 5ml every 4 to 6 hours as required',
'Take 2.5ml every 4 to 6 hours when required. Maximum of 6 doses in 24 hours.',
'Take 2.5ml four times a day',
'Take 2.5ml four times a day for 10 days',
'Take 2.5ml four times a day for 5 days',
'Take 2.5ml four times a day for 7 days',
'Take 2.5mL four times each day for 5 days',
'Take 2.5ml once or twice a day',
'Take 2.5ml three or four times a day when required',
'Take 2.5ml three times a day for 3 days',
'Take 2.5ml three times a day for 5 days',
'Take 2.5ml three times a day for 7 days',
'Take 2.5ml three times daily',
'Take 2.5ml three times daily for 10 days',
'Take 2.5ml to 5ml every four to six hours when required. Maximum of 4 doses in 24 hours',
'Take 2.5ml to 5ml every morning',
'Take 2.5ml twice a day',
'Take 2.5ml twice a day for 3 days',
'Take 2.5ml twice a day for 5 days',
'Take 2.5ml twice a day for 7 days',
'Take 2.5ml twice a day when required',
'Take 2.5ml up to every 4 hours at first, then increase to 5ml every 4 hours as required',
'Take 2/3rds of a sachet now as a single dose. Repeat after 2 weeks.',
'Take 2/3rds sachet now.',
'Take 3 tablets at night',
'Take 5 to 10mls 1 hour after meals and at bedtime, or as required.',
'Take 5 to 10mls four times a day between meals and at bedtime, or as required.',
'Take 5ml as a single dose.',
'Take 5ml at night.',
'Take 5ml at night.           *Repeat 2 times*',
'Take 5mL four times each day for 5 days',
'Take 5ml three times a day',
'Take 5ml three times a day for 7 days.',
'Take 5ml to 10ml after meals and at bedtime',
'Take 5ml to 10ml every morning',
'Take 5ml to 10ml three times a day',
'Take 5ml to 15ml at night as directed',
'Take 5ml to 15ml times a day after meals and at bedtime',
'Take 5ml to 7.5ml three or four times a day',
'Take 5ml twice a day',
'Take 5ml twice a day for 7 days.',
'Take 5ml up to every 4 to 6 hours. ?Maximum 6 doses in 24 hours.',
'Take 7.5mg per kg bodyweight twice a day for 7 days',
'Take 7.5ml at night. Increase up to 5ml five times a day if needed.',
'Take 7.5ml once a day for 3 days',
'Take 7.5ml to 10ml  three or four times a day',
'Take 7.5ml twice a day for 3 days',
'Take 7.5ml twice a day for 5 days',
'Take 7.5ml twice a day for 7 days',
'Take a quarter of a tablet daily after a meal',
'Take as a single dose by mouth',
'Take as a single dose.',
'Take as directed',
'Take as directed by the package insert',
'Take as directed by your doctor',
'Take eight tablets daily as a single dose',
'Take eight tablets every morning',
'Take five capsules at night',
'Take five tablets at night',
'Take five tablets daily',
'Take five tablets every morning',
'Take five tablets morning and night.',
'Take five tablets together as one dose',
'Take four  tablets once a day for 3 days, then take one tablet daily.',
'Take four and a half tablets every morning',
'Take four tablets as a single dose',
'Take four tablets daily',
'Take four tablets daily, as a single dose, for 3 days',
'Take four tablets daily, as a single dose, for 5 days',
'Take four tablets every morning',
'Take four tablets in the morning and take three tablets at night.',
'Take four tablets morning and night.',
'Take four tablets together as one dose',
'Take four tablets twice a day',
'Take half a 5ml spoonful every morning and evening as needed',
'Take half a tablet 3 times a day for 2 weeks, then increase to one tablet 3 times a day',
'Take half a tablet at night',
'Take half a tablet at night for 2 weeks',
'Take half a tablet at night for 4 nights, then increase to one tablet at night',
'Take half a tablet at night for 4 nights, then take one tablet at night for next week, then take one tablet three times a day',
'Take half a tablet daily after a meal',
'Take half a tablet daily for 7 days, then if required increase to one tablet daily.',
'Take half a tablet every 4 to 6 hours when required. Maximum of 6 doses in 24 hours.',
'Take half a tablet on day 1, then increase to one tablet daily from day 2. Increase to 2 tablets daily on day 6 if required.',
'Take half a tablet on first day, then take one tablet twice a day',
'Take half a tablet three times a day after meals, increasing after 2 to 3 days, to one tablet three times a day if required',
'Take half a tablet three times a day for 1 or 2 weeks, then increase to one tablet three times a day as directed',
'Take half a tablet twice a day',
'Take half a tablet twice a day, after meals',
'Take half to one level 5ml spoonful morning and evening as needed',
'Take half to one sachet once a day, added to food',
'Take half to one sachet once or twice a day, added to food.',
'Take nine tablets every morning',
'Take one  tablet every 4 hours. Maximum 8 tablets in 24 hours',
'Take one 3 times a day when required',
'Take one 4 times a day',
'Take one 5ml spoonful 3 or 4 times a day when required',
'Take one 5ml spoonful 3 times a day when required',
'Take one 5ml spoonful at night for 2 weeks then reduce to half a 5ml spoonful for 2 weeks',
'Take one 5mL spoonful at night if needed',
'Take one 5ml spoonful at night.',
'Take one 5ml spoonful daily',
'Take one 5ml spoonful daily when required',
'Take one 5ml spoonful daily, or as directed',
'Take one 5mL spoonful each day',
'Take one 5ml spoonful every 4 to 6 hours when required. Maximum of 4 doses in 24 hours',
'Take one 5ml spoonful every 4 to 6 hours when required. Maximum of 6 doses in 24 hours.',
'Take one 5ml spoonful for 3 days',
'Take one 5ml spoonful four times a day',
'Take one 5ml spoonful four times a day for 10 days',
'Take one 5ml spoonful four times a day for 3 days',
'Take one 5ml spoonful four times a day for 5 days',
'Take one 5ml spoonful four times a day for 5 days',
'Take one 5ml spoonful four times a day for 7 days',
'Take one 5mL spoonful four times each day for 5 days',
'Take one 5mL spoonful four times each day for 5days',
'Take one 5ml spoonful once a day for 3 days',
'Take one 5ml spoonful three or four times a day when required',
'Take one 5ml spoonful three times a day',
'Take one 5ml spoonful three times a day for 10 days',
'Take one 5ml spoonful three times a day for 3 days',
'Take one 5ml spoonful three times a day for 7 days',
'Take one 5ml spoonful three times a day, or as directed',
'Take one 5ml spoonful twice a day',
'Take one 5ml spoonful twice a day for 10 days',
'Take one 5ml spoonful twice a day for 3 days',
'Take one 5ml spoonful twice a day for 5 days',
'Take one 5ml spoonful twice a day for 7 days',
'Take one and a half tablets at night',
'Take one and a half tablets at night for 2 weeks',
'Take one at night',
'Take one at night for 7 days, then take two at night for 7 days, then take three at night.',
'Take one at night for 7 days, then two at night for 7 days',
'Take one at night when required for itching',
'Take one at night. Increase to one tablet four times a day if needed.',
'Take one capsule 3 times a day after meals, increasing to 4 times a day if required',
'Take one capsule after intercourse as directed.',
'Take one capsule at night',
'Take one capsule at night for 4 weeks',
'Take one capsule at night for 8 weeks',
'Take one capsule at night, swallow whole with fluid',
'Take one capsule before, during or up to one hour after each main meal. Maximum 3 caps daily',
'Take one capsule daily',
'Take one capsule daily for 10 days',
'Take one capsule daily for 14 days',
'Take one capsule daily for 2 days, then increase to two capsules daily',
'Take one capsule daily for 4 days',
'Take one capsule daily for 4 weeks',
'Take one capsule daily for 6 weeks',
'Take one capsule daily for 8 weeks',
'Take one capsule daily with a main meal',
'Take one capsule daily with food',
'Take one capsule each day',
'Take one capsule each morning',
'Take one capsule each morning, on an empty stomach.',
'Take one capsule every morning , on an empty stomach, for 4 weeks',
'Take one capsule every morning, on an empty stomach, for 8 weeks',
'Take one capsule four times a day',
'Take one capsule four times a day for 10 days',
'Take one capsule four times a day for 5 days',
'Take one capsule four times a day for 7 days',
'Take one capsule four times daily',
'Take one capsule four times each day for 5 days',
'Take one capsule on alternate days',
'Take one capsule on Monday, Wednesday and Friday nights.',
'Take one capsule three times a day',
'Take one capsule three times a day for 10 days',
'Take one capsule three times a day for 3 days',
'Take one capsule three times a day for 5 days',
'Take one capsule three times a day for 7 days',
'Take one capsule three times a day for one week',
'Take one capsule three times a day if required',
'Take one capsule three times a day with food',
'Take one capsule three times a day. Increase to a maximum of 5 capsules a day if needed.',
'Take one capsule twice a day',
'Take one capsule twice a day for 4 weeks',
'Take one capsule twice a day for one week.',
'Take one capsule twice a day with fluid',
'Take one capsule twice a day with food',
'Take one capsule twice a day, increasing by 1 capsule every 3 or 4 days if required to one capsule 4 times a day',
'Take one capsule twice a day, on an empty stomach, for one week.',
'Take one capsule twice a day, swallow whole with fluid',
'Take one capsule twice a week',
'Take one daily',
'Take one daily when required',
'Take one every 4 to 6 hours when required. Maximum of 4 doses in 24 hours',
'Take one every 4 to 6 hours when required. Maximum of 6 tablets in 24 hours',
'Take one of each type of tablets twice a day with food',
'Take one or two  tablets every 4 to 6 hours, up to a maximum of 8 tablets a day.',
'Take one or two 5ml spoonfuls every four to six hours when required. Maximum of 4 doses in 24 hours',
'Take one or two 5ml spoonsful at night',
'Take one or two at night when required for itching',
'Take one or two capsules at night',
'Take one or two capsules once or twice a day if required',
'Take one or two capsules up to four times a day',
'Take one or two capsules up to three times a day as needed',
'Take one or two every 4 hours when required for pain relief. Maximum of 8 tablets in 24 hours',
'Take one or two every 4 to 6 hours when required',
'Take one or two every 4 to 8 hours when required for nausea and vomiting',
'Take one or two tablets 1 hour after meals and at bedtime, or as required',
'Take one or two tablets daily if required.',
'Take one or two tablets every 4 hours when necessary. Maximum 8 tablets in 24 hours.',
'Take one or two tablets every 4 hours. Maximum 8 tablets in 24 hours.',
'Take one or two tablets every 4 to 6 hours when required, up to a maximum of 8 tablets in 24 hours',
'Take one or two tablets every 4 to 6 hours, up to a maximum of 8 tablets in 24 hours.',
'Take one or two tablets every 4 to 8 hours as required to control nausea',
'Take one or two tablets every four hours. Maximum 8 tablets in 24 hours',
'Take one or two tablets every four to six hours when required, up to a maximum of 6 tablets in 24 hours',
'Take one or two tablets four times a day as required. Do not take more than 8 tablets in 24 hours.',
'Take one or two tablets four times a day if required',
'Take one or two tablets four times a day if required. Do not take more than eight tablets in 24 hours.',
'Take one or two tablets once or twice a day if required, up to a maximum of 4 in 24 hours.',
'Take one or two tablets three times a day',
'Take one or two tablets three times a day before meals and at night.',
'Take one sachet 2 or 3 times a day added to food',
'Take one sachet dissolved in water morning and evening',
'Take one sachet now.',
'Take one sachet now. Repeat after 2 weeks.',
'Take one sachet twice a day for 2 days',
'Take one tablet  daily following instructions on pack and take a second tablet daily for 12 days each month as directed on pack.',
'Take one tablet 3 times a day after meals, increasing to 4 times a day if required.',
'Take one tablet 3 times a day, increasing as required,  to 2 tablets 3 times a day',
'Take one tablet 3 times a day, increasing by one tablet daily. or on alternate days, if required,  to a maximum of 8 tablets daily',
'Take one tablet after intercourse as directed.',
'Take one tablet an hour before the anticipated stressful situation',
'Take one tablet an hour before the anticipated stressful situation. Take another tablet after 4-6 hours if required.',
'Take one tablet at 8am and another at 3pm',
'Take one tablet at bedtime',
'Take one tablet at bedtime, may increase up to four times a day if necessary for sickness',
'Take one tablet at night',
'Take one tablet at night for 2 weeks',
'Take one tablet at night for 2 weeks, then reduce to half a tablet for 2 weeks',
'Take one tablet at night for 4 nights, then take two tablets at night for 4 nights',
'Take one tablet at night for 4 weeks',
'Take one tablet at night for 5 days then change to 25mg tablets',
'Take one tablet at night for 5 days, then increase to 2 tablets at night',
'Take one tablet at night for 7 days then increase to 2 tablets at night for 7 days, then to 3 tablets at night',
'Take one tablet at night for 7 nights, then take two tablets at night for 7 nights',
'Take one tablet at night for 8 weeks',
'Take one tablet at night if needed',
'Take one tablet at night with food',
'Take one tablet at night. Increase at weekly intervals if needed to a maximum of 6 tablets in 24 hours',
'Take one tablet at night. Increase to one tablet three times a day if needed.',
'Take one tablet at night. Increase to two tablets if needed',
'Take one tablet at onset of migraine attack. Take another one tablet if migraine recurs, up to a maximum of 3 tablets in 24 hours.',
'Take one tablet at onset of migraine attack. Take another one tablet if migraine recurs, up to a maximum of 6 tablets in 24 hours.',
'Take one tablet daily',
'Take one tablet daily after food',
'Take one tablet daily following instructions on pack for 14 days, then add second tablet daily for 14 days according to instructions on pack.',
'Take one tablet daily following instructions on pack.',
'Take one tablet daily following the instructions on the pack.',
'Take one tablet daily for 1 week, then if required increase to one and a half tablets daily.',
'Take one tablet daily for 1 week, then increase to two tablets daily ',
'Take one tablet daily for 2 days, then increase to two tablets daily.',
'Take one tablet daily for 2 weeks, then increase to two tablets daily for next 2 weeks',
'Take one tablet daily for 21 days, following instructions on pack.',
'Take one tablet daily for 7 days',
'Take one tablet daily for six weeks.',
'Take one tablet daily for two weeks, then increase to two daily for two weeks then to three daily.',
'Take one tablet daily in the order indicated on the packet',
'Take one tablet daily with food',
'Take one tablet daily, increasing up to three tablets a day if necessary.',
'Take one tablet daily, may be increased to two tablets daily if necessary.',
'Take one tablet each day',
'Take one tablet each day for 21 days then have 7 pill-free days',
'Take one tablet each morning',
'Take one tablet each morning for 4 weeks, then take two tablets each morning for 4 weeks.',
'Take one tablet each morning for 8 weeks',
'Take one tablet every 3 to 4 hours ?up to a maximum of 6 tablets in 24 hours.',
'Take one tablet every 3 to 4 hours ?up to a maximum of 8 tablets in 24 hours',
'Take one tablet every 4 to 6 hours when necessary .Maximum 6 tablets daily.',
'Take one tablet every four hours. Maximum 6 tablets in 24 hours.',
'Take one tablet every four to six hours. Maximum 6 tablets in 24 hours.',
'Take one tablet every four to six hours. Maximum 6 tablets in 24 hours.',
'Take one tablet every morning',
'Take one tablet every third night to aid sleep',
'Take one tablet five times a day for 5 days',
'Take one tablet five times a day for 7 days',
'Take one tablet four times a day',
'Take one tablet four times a day after food.',
'Take one tablet four times a day at the same time as NSAID drug',
'Take one tablet four times a day for 10 days',
'Take one tablet four times a day for 3 days',
'Take one tablet four times a day for 4 weeks.',
'Take one tablet four times a day for 5 days',
'Take one tablet four times a day for 7 days',
'Take one tablet four times a day if required.',
'Take one tablet four times a day, or as directed by your doctor for dosage adjustment',
'Take one tablet four times each day for 5 days',
'Take one tablet in the morning and take two tablets at night',
'Take one tablet in the morning for 4 weeks.',
'Take one tablet on alternate mornings',
'Take one tablet on alternate mornings (with the two 5mg tablets)',
'Take one tablet on Monday, Wednesday and Friday nights.',
'Take one tablet per 12.5kg of bodyweight each day',
'Take one tablet three nights a week.',
'Take one tablet three or four times a day',
'Take one tablet three or four times a day during period',
'Take one tablet three times a day',
'Take one tablet three times a day after food',
'Take one tablet three times a day at the same time as NSAID drug',
'Take one tablet three times a day during an acute attack, increase to a maximum of 6 tablets daily if required.',
'Take one tablet three times a day during period',
'Take one tablet three times a day for 10 days',
'Take one tablet three times a day for 14 days.',
'Take one tablet three times a day for 3 days',
'Take one tablet three times a day for 5 days',
'Take one tablet three times a day for one week',
'Take one tablet three times a day from day 5 to day 25 of cycle',
'Take one tablet three times a day if required',
'Take one tablet three times a day with or after food',
'Take one tablet three times a day, increase to four times a day if required',
'Take one tablet three times a day, increasing by 1 tablet each day to a maximum of  two tablets four times a day',
'Take one tablet three times a day, preferably 20 minutes before meals',
'Take one tablet twice a day',
'Take one tablet twice a day  at the same time as NSAID DRUG',
'Take one tablet twice a day after food',
'Take one tablet twice a day at the same time as NSAID drug',
'Take one tablet twice a day for 1 week increased if required to one and a half tablets twice a day',
'Take one tablet twice a day for 10 days',
'Take one tablet twice a day for 14 days.',
'Take one tablet twice a day for 2 weeks, then increase to two tablets twice a day',
'Take one tablet twice a day for 3 days',
'Take one tablet twice a day for 4 weeks',
'Take one tablet twice a day for 5 days',
'Take one tablet twice a day for 5 days then increase by one tablet every 5 days until relief obtained or you are up to 6 tablets daily',
'Take one tablet twice a day for 7 days',
'Take one tablet twice a day for 7 days then increase by one tablet every 7 days until relief obtained or you are up to 6 tablets daily',
'Take one tablet twice a day for 7 days, then increase to three times a day if relief not yet gained',
'Take one tablet twice a day for 7 days, then take two tablets twice a day for 7 days.',
'Take one tablet twice a day for one week',
'Take one tablet twice a day from day 5 to day 25 of cycle',
'Take one tablet twice a day with food',
'Take one tablet twice a day with or after food',
'Take one tablet twice a day, increased if required after 1 week treatment, to 1&a half tablets twice a day',
'Take one tablet two to four times a day WITH the Non Steroidal Anti Inflammatory Drug.',
'Take one tablet up to three times a day for relief of sickness',
'Take one tablet up to three times a day if required.',
'Take one tablets every four to six hours when necessary. Maximum 6 tablets in 24 hours.',
'Take one tablets every four to six hours when necessary. Maximum 6 tablets in 24 hours.',
'Take one to three 5ml spoonfuls at night when required for itching',
'Take one to three 5ml spoonsful at night',
'Take one to three capsules at night',
'Take one to three tablets at night',
'Take one to three tablets every four to six hours when required, up to 13 tablets a day',
'Take one twice a day',
'Take one twice a day after food',
'Take one white tablet daily for 70 days (starting on 5th day of cycle if present), then take one blue tablet daily for 14 days, then take one yellow t',
'Take one, two or three every 4 to 6 hours when required. Maximum of 13 tablets in 24 hours.',
'Take one, two or three every 4 to 6 hours when required. Maximum of 13 tablets in 24 hours',
'Take seven tablets daily as a single dose',
'Take seven tablets every morning',
'Take six tablets at night',
'Take six tablets daily',
'Take six tablets daily as a single dose',
'Take six tablets daily for one week, then follow the instructions from your doctor.',
'Take six tablets every morning',
'Take six tablets morning and night.',
'Take ten tablets daily as a single dose',
'Take the contents of one sachet 4 times a day',
'Take the tablets following  the instructions on the pack',
'Take three 5ml spoonfuls twice a day',
'Take three and a half tablets every morning',
'Take three at night',
'Take three capsules at night',
'Take three capsules at night for 4 nights, then take four capsules at night for 4 nights',
'Take three capsules each morning',
'Take three capsules every morning and two every afternoon',
'Take three capsules four times a day',
'Take three capsules twice a day',
'Take three or two and a half tablets on alternate mornings',
'Take three tablets at bedtime',
'Take three tablets at night',
'Take three tablets at night for 4 nights, then take four tablets at night for 4 nights',
'Take three tablets daily',
'Take three tablets each morning during acute gout',
'Take three tablets each morning for 4 weeks, then take four tablets each morning for 4 weeks.',
'Take three tablets each morning for ten days.',
'Take three tablets every 4 to 6 hours as required for pain, up to a maximum of 13 tablets in 24 hours.',
'Take three tablets every morning',
'Take three tablets or two and a half tablets on alternate mornings',
'Take three tablets three times a day',
'Take three tablets twice a day for 2 weeks, then increase to four tablets twice a day',
'Take three tablets twice a day for 3 days, then increase to four tablets twice daily for 3 days, then increase to five tablets twice daily',
'Take three tablets twice a day.',
'Take twelve tablets daily as a single dose',
'Take two  tablets every 4 to 6 hours, up to a maximum of 8 tablets in 24 hours.',
'Take two 3 times a day',
'Take two 4 times a day',
'Take two 5ml spoonfuls 3 times a day',
'Take two 5ml spoonfuls 3 times a day when required',
'Take two 5ml spoonfuls 4 times a day',
'Take two 5ml spoonfuls at night for 2 weeks then reduce by half a 5ml spoonful ( 2.5ml) every 2 weeks',
'Take two 5ml spoonfuls daily when required',
'Take two 5ml spoonfuls in the morning and take three 5ml spoonfuls at night',
'Take two 5ml spoonfuls once a day',
'Take two 5ml spoonfuls three or four  times a day when required',
'Take two 5ml spoonfuls twice a day',
'Take two 5ml spoonfuls up to three times a day. Increase to a maximum of ten 5ml spoonfuls a day if necessary',
'Take two 5ml spoonsful at bedtime. Increase to four 5ml spoonsful if needed.',
'Take two 5ml spoonsful once a day for 3 days',
'Take two 5ml spoonsful three or four times a day',
'Take two 5ml spoonsful three times a day, or as directed',
'Take two 5ml spoonsful twice a day for 5 days',
'Take two and a half tablets daily',
'Take two and a half tablets every morning',
'Take two at night for 7 days, then three at night for 7 days, then four at night for 7 days.',
'Take two capsules at night for 1 week, then take one capsule in the morning and two at night for 1 week, then take two capsules twice a day',
'Take two capsules at night, swallow whole with fluid',
'Take two capsules at night.',
'Take two capsules daily',
'Take two capsules daily for 10 days',
'Take two capsules daily for 3 days',
'Take two capsules each day',
'Take two capsules each day for 7 days',
'Take two capsules each morning',
'Take two capsules each morning and take three capsules at night',
'Take two capsules four times a day',
'Take two capsules twice a day',
'Take two capsules twice a day for 1 day only',
'Take two capsules twice a day for 1 day only. Repeat every 2 to 4 weeks as directed.',
'Take two capsules twice a day for one week',
'Take two capsules twice a day with fluid',
'Take two capsules twice a day with food',
'Take two capsules twice a day, swallow whole with fluid',
'Take two every 6 to 8 hours when required',
'Take two on the first day and then take one daily',
'Take two sachets at onset of attack, then repeat every four hours if required up to a maximum of 6 in 24 hours.',
'Take two tablets an hour before the anticipated stressful situation',
'Take two tablets at bedtime',
'Take two tablets at first then take one tablet three times a day for 7 days',
'Take two tablets at night',
'Take two tablets at night for 2 weeks',
'Take two tablets at night for 2 weeks, then reduce by half a tablet every 2 weeks',
'Take two tablets at night for 7 nights',
'Take two tablets at night with food',
'Take two tablets at night. Increase to four tablets if needed.',
'Take two tablets at onset of attack, then repeat every four hours if required up to a maximum of 6 tablets in 24 hours.',
'Take two tablets at onset of attack, then repeat every four hours if required up to a maximum of 8 tablets in 24 hours.',
'Take two tablets daily',
'Take two tablets daily for 7 days',
'Take two tablets daily with food.',
'Take two tablets every 4 to 6 hours, up to a maximum of 8 tablets in 24 hours.',
'Take two tablets every four to six hours  when required up to a maximum of 8 tablets in 24 hours.',
'Take two tablets every four to six hours for pain relief up to a maximum of 8 tablets in 24 hours.',
'Take two tablets every four to six hours, dissolved in water, for pain relief. Maximum dose 8 tablets in 24 hours.',
'Take two tablets every morning',
'Take two tablets every six hours when required for pain relief, up to a maximum of 8 tablets in 24 hours.',
'Take two tablets four times a day',
'Take two tablets four times a day for 10 days',
'Take TWO tablets now and then take ONE tablet three times a day for five days',
'Take TWO tablets now and then take ONE tablet three times a day for seven days',
'Take two tablets now and then take one tablet three times a day for seven days',
'Take two tablets once a day for 3 days, then take one tablet daily.',
'Take two tablets or three tablets on alternate mornings',
'Take two tablets or two and a half tablets on alternate mornings',
'Take two tablets three times a day',
'Take two tablets three times a day after meals',
'Take two tablets three times a day during an acute attack.',
'Take two tablets three times a day for 7 days',
'Take two tablets twice a day',
'Take two tablets twice a day after food',
'Take two tablets twice a day and take one tablet at night',
'Take two tablets twice a day at the same time as NSAID drug.',
'Take two tablets twice a day for 10 days',
'Take two tablets twice a day for 2 weeks, increasing to three tablets twice a day if symptoms not controlled.',
'Take two tablets twice a day for 4 weeks.',
'Take two tablets twice a day for 5 days',
'Take two tablets twice each day',
'Take two to five 5ml spoonfuls at night when required for itching',
'Take two twice a day',
'The contents of one sachet to be dissolved in water and taken three times a day as directed.',
'The contents of one vial (one spray) to be sprayed into one nostril at onset of migraine. Repeat not less than 2 hours later if migraine recurs.',
'To be applied by the nurse',
'To be injected as directed by your doctor',
'To be measured and fitted in the pharmacy',
'To be used by the nurse',
'To be used by the nurse to clean the ulcer',
'Two below knee length stockings of Class II  compression, circular knit, to be measured and fitted in the pharmacy',
'Two below knee length stockings of Class II medium compression, to be measured and fitted in the pharmacy',
'Two pairs of Class II compression, circular knit thigh length stockings to be measured and fitted in the pharmacy',
'Two pairs of Class II medium compression, thigh length stockings to be measured and fitted in the pharmacy',
'Two sprays into each nostril at bedtime.',
'Use  as directed',
'Use as a moisturiser, especially after bathing',
'Use as a moisturiser, especially after bathing',
'Use as directed by your doctor',
'Use as required to relieve symptoms',
'use as#',
'Use before bowel movements. Do not continue with this treatment for more than 1 week.',
'Use daily as needed',
'Use instead of soap',
'Use one enema as needed',
'Use one or two tablets daily during an acute attack. Place high up between the upper lip and gum and leave to dissolve.',
'Use one to three times a week',
'Use regularly as a moisturiser, especially after bathing',
'Use regularly as a moisturiser, especially after bathing.  Can be used as a soap substitute',
'Use regularly as a moisturiser, especially after washing hands',
'Use to aid inhalation',
'Use to make a wick',
]
